# MTI830 — Pipeline de sélection des joueurs et des parties

Ce notebook exécute la pipeline suivante :

1. Charger une liste manuelle de joueurs candidats depuis `players.txt`
2. Télécharger leurs parties brutes via l'API Lichess/Berserk
3. Sauvegarder le brut API (`raw_games_by_player.json`)
4. Construire `player_games_raw` via `build_player_games(...)`
5. Sauvegarder `player_games_raw.json`
6. Appliquer `select_player_games(...)`
7. Inspecter les résultats

Avant d'exécuter le notebook, vérifie que :

- `players.txt` existe à la racine du projet
- tes modules `src.ingestion.player_sampling`, `src.dataset.io`, `src.dataset.select_players` sont à jour
- ton token API Lichess est disponible

## 0. Imports et configuration

In [5]:
from pathlib import Path
import os
import sys
sys.path.append(os.path.abspath(".."))
import json
from dotenv import load_dotenv
import time
import datetime 
from datetime import timedelta

import pandas as pd
import berserk

from src.ingestion.player_sampling import collect_raw_games_for_players
from src.dataset.io import (
    save_raw_games_by_player,
    load_raw_games_by_player,
    build_player_games_raw_from_api_dump,
    save_player_games_raw,
    load_player_games_raw,
    save_raw_games_for_one_player,
    list_downloaded_player_ids,
    load_raw_games_by_player_from_directory,
    save_player_games_selected,
    load_player_games_selected
)
from src.dataset.select_players import PlayerSelectionConfig, select_player_games

In [18]:
# Ajuste ce chemin si nécessaire
PLAYERS_TXT_PATH = Path("../data/player_candidates/players.txt")
RAW_GAMES_JSON_PATH = Path("../data/raw/raw_games_by_player.json")
PLAYER_GAMES_RAW_JSON_PATH = Path("../data/raw/player_games_raw.json")
RAW_GAMES_BY_PLAYER_DIR = Path("../data/raw/by_player")
FAILED_PLAYERS_PATH = Path("../data/raw/failed_players.txt")
PLAYER_GAMES_SELECTED_JSON_PATH = Path("../data/selected/player_games_selected.json")
SELECTED_PLAYERS_TXT_PATH = Path("../data/selected/selected_players.txt")
SELECTION_SUMMARY_JSON_PATH = Path("../data/selected/selection_summary.json")
SELECTION_CONFIG_JSON_PATH = Path("../data/selected/selection_config.json")
GAMES_FINAL_JSON_PATH = Path("../data/enriched/games_final.json")
FINAL_DATASET_JSON_PATH = Path("../data/final/final_dataset.json")

# Pour un premier test, garde une limite raisonnable
MAX_GAMES_PER_PLAYER = 1021
SLEEP_SECONDS = 0.5

# Option pratique : recharger depuis disque au lieu de retélécharger
USE_EXISTING_RAW_GAMES_JSON = False
USE_EXISTING_PLAYER_GAMES_RAW_JSON = False

START_2025 = berserk.utils.to_millis(datetime.datetime(2025, 1, 1))
END_2026 = berserk.utils.to_millis(datetime.datetime(2026, 1, 1))

## 1. Création du client Berserk

In [13]:
# Option 1 : variable d'environnement LICHESS_API_TOKEN
load_dotenv("../.env")
token = os.getenv('LICHESS_API_TOKEN')

# Option 2 : décommente et colle temporairement ton token si besoin
# token = 'COLLE_ICI_TON_TOKEN'

if not token:
    raise ValueError('Token API introuvable. Définis LICHESS_API_TOKEN ou renseigne token dans la cellule.')

session = berserk.TokenSession(token)
client = berserk.Client(session=session)

print('Client Berserk créé avec succès')

Client Berserk créé avec succès

## 2. Charger la liste manuelle de joueurs

In [14]:
def load_player_ids_from_txt(path: str | Path) -> list[str]:
    lines = Path(path).read_text(encoding='utf-8').splitlines()
    return [line.strip() for line in lines if line.strip()]

seed_player_ids = load_player_ids_from_txt(PLAYERS_TXT_PATH)
print(f'{len(seed_player_ids)} joueurs chargés')
print(seed_player_ids[:15])

downloaded_player_ids = set(list_downloaded_player_ids(RAW_GAMES_BY_PLAYER_DIR))
remaining_player_ids = [p for p in seed_player_ids if p not in downloaded_player_ids]

print(f"Déjà téléchargés : {len(downloaded_player_ids)}")
print(f"Restants à télécharger : {len(remaining_player_ids)}")

1892 joueurs chargés
['VW-Leoo', 'Lalsahab8855', 'ElizavetaVesna', 'nevo01', 'plotogamer', 'thelegendxd8bpq', 'MattMatze', 'ramya254', 'ajedrecista28', 'igraclagan', 'gr33do', 'sefeydn', 'MilanKontic', 'std_priority_queue', 'cool_shine']
Déjà téléchargés : 867
Restants à télécharger : 1023

## 3. Télécharger ou recharger `raw_games_by_player`

In [15]:
downloaded_player_ids = set(list_downloaded_player_ids(RAW_GAMES_BY_PLAYER_DIR))
remaining_player_ids = [p for p in seed_player_ids if p not in downloaded_player_ids]

print(f"Déjà téléchargés : {len(downloaded_player_ids)}")
print(f"Restants à télécharger : {len(remaining_player_ids)}")
print(remaining_player_ids[:10])

Déjà téléchargés : 867
Restants à télécharger : 1023
['vebbev', 'Velociraptor1510', 'starfox_88', 'Fnntnn', 'BENHAIMED-CMPT3', 'imbayog', 'Egordan', 'sunil_goyal', 'nowjohn', 'JohnPion']

In [16]:
failed_players = []

for idx, player_id in enumerate(remaining_player_ids, start=1):
    player_json_path = RAW_GAMES_BY_PLAYER_DIR / f"{player_id}.json"

    # Garde-fou de reprise
    if player_json_path.exists():
        print(f"[SKIP] {player_id} déjà téléchargé")
        continue

    try:
        # 1) Données publiques du joueur
        user_data = client.users.get_public_data(player_id)

        if not user_data or "createdAt" not in user_data:
            raise ValueError("Champ 'createdAt' introuvable dans get_public_data.")

        created_at = user_data["createdAt"]

        # 2) Fenêtre d'observation : 6 mois après création du compte
        since = berserk.utils.to_millis(created_at)
        until = berserk.utils.to_millis(created_at + timedelta(days=183))

        # 3) Export des parties dans cette fenêtre
        games = client.games.export_by_player(
            player_id,
            max=MAX_GAMES_PER_PLAYER,
            since=since,
            until=until,
            perf_type="rapid",
            opening=True,
        )
        games = list(games)

        # 4) Filtrage local complémentaire
        games = [
            g for g in games
            if isinstance(g, dict)
            and g.get("rated") is True
            and (
                str(g.get("speed") or "").lower() == "rapid"
                or str(g.get("perf") or "").lower() == "rapid"
            )
            and str(g.get("status") or "").lower() not in {"created", "started", ""}
        ]

        # 5) Tri du plus ancien au plus récent
        games = sorted(games, key=lambda g: g.get("createdAt"))

        # 6) Sauvegarde immédiate
        save_raw_games_for_one_player(
            player_id=player_id,
            games=games,
            directory=RAW_GAMES_BY_PLAYER_DIR,
        )

        print(
            f"[{idx}/{len(remaining_player_ids)}] "
            f"{player_id} | createdAt={created_at} | {len(games)} parties sauvegardées"
        )

    except Exception as e:
        failed_players.append(player_id)
        print(f"[ERREUR] {player_id}: {e}")

        with FAILED_PLAYERS_PATH.open("a", encoding="utf-8") as f:
            f.write(player_id + "\n")

        # si rate limit, pause plus longue
        if "429" in str(e) or "Too Many Requests" in str(e):
            print("Pause longue après rate limit...")
            time.sleep(30)

    time.sleep(SLEEP_SECONDS)

[ERREUR] vebbev: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] Velociraptor1510: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] starfox_88: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] Fnntnn: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] BENHAIMED-CMPT3: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] imbayog: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] Egordan: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] sunil_goyal: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] nowjohn: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] JohnPion: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] D171016350: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] deVKim: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] unkownahirishere: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] Simo01101110: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] mco1984: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] Pandavosem: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] paps1922: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] Si3mand3ro: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] AjBhinder: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] berhanunathaniel01: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] prolly_getting: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] ybis: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] RUDOLPHUS-BACCHUS: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] Egleand: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] menadorui: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] e4_itsmee: Champ 'createdAt' introuvable dans get_public_data.
[27/1023] ahmad189 | createdAt=2023-05-04 19:43:08.545000+00:00 | 570 parties sauvegardées
[28/1023] ManuelPedroSanchez | createdAt=2020-06-16 18:22:15.699000+00:00 | 0 parties sauvegardées
[29/1023] jtgualt | createdAt=2022-03-08 02:02:46.814000+00:00 | 400 parties sauvegardées
[30/1023] Eji_Eggy | createdAt=2022-10-24 18:16:15.892000+00:00 | 472 parties sauvegardées
[31/1023] Osgara | createdAt=2024-06-29 04:16:30.730000+00:00 | 1050 parties sauvegardées
[32/1023] Ali976 | createdAt=2022-01-15 10:52:17.998000+00:00 | 1 parties sauvegardées
[33/1023] booger99 | createdAt=2023-01-05 20:09:07.767000+00:00 | 1003 parties sauvegardées
[34/1023] TEO55 | createdAt=2023-04-05 15:57:15.525000+00:00 | 145 parties sauvegardées
[35/1023] TheoKroner | createdAt=2023-03-24 15:51:44.163000+00:00 | 4 parties sauvegardées
[36/1023] luca_gazz | createdAt=2017-12-25 23:38:00.245000+00:00 | 0 parties sauvegardées
[ERREUR] yasinserefler: Champ 'createdAt' introuvable dans get_public_data.
[ERREUR] GoldSightlyWorm: Champ 'createdAt' introuvable dans get_public_data.
[39/1023] GagikSim | createdAt=2021-11-22 19:58:55.803000+00:00 | 221 parties sauvegardées
[40/1023] Gray_Antimateria | createdAt=2017-12-24 03:16:21.295000+00:00 | 0 parties sauvegardées
[41/1023] MagierPL | createdAt=2021-03-21 12:19:17.819000+00:00 | 0 parties sauvegardées
[42/1023] bdebbagi | createdAt=2022-07-03 12:22:33.716000+00:00 | 7 parties sauvegardées
[43/1023] MashaVarya | createdAt=2024-08-16 12:12:17.194000+00:00 | 266 parties sauvegardées
[44/1023] greybustertv | createdAt=2024-09-19 13:16:35.948000+00:00 | 1050 parties sauvegardées
[45/1023] JuanMaza | createdAt=2017-12-19 04:47:08.966000+00:00 | 0 parties sauvegardées
[46/1023] Adrian7DM | createdAt=2022-04-28 18:59:39.154000+00:00 | 184 parties sauvegardées
[47/1023] ElMateArgentino | createdAt=2019-04-11 23:46:37.149000+00:00 | 0 parties sauvegardées
[48/1023] TolekBanan69 | createdAt=2020-05-20 18:23:29.266000+00:00 | 0 parties sauvegardées
[49/1023] RayGomez | createdAt=2024-10-18 04:02:21.323000+00:00 | 1049 parties sauvegardées
[50/1023] Pippen19 | createdAt=2023-02-07 07:55:07.548000+00:00 | 160 parties sauvegardées
[51/1023] fox_candy | createdAt=2020-12-05 13:35:16.285000+00:00 | 0 parties sauvegardées
[52/1023] DebsdaBomB | createdAt=2020-07-14 06:41:12.665000+00:00 | 0 parties sauvegardées
[53/1023] michio_alvannanda | createdAt=2017-05-17 05:44:27.013000+00:00 | 0 parties sauvegardées
[54/1023] Soymalito | createdAt=2020-11-07 17:56:48.873000+00:00 | 0 parties sauvegardées
[55/1023] pesutti | createdAt=2025-01-12 00:29:24.607000+00:00 | 708 parties sauvegardées
[56/1023] matkor | createdAt=2023-06-23 10:09:13.098000+00:00 | 254 parties sauvegardées
[57/1023] bill-bishop | createdAt=2024-04-09 12:36:09.360000+00:00 | 322 parties sauvegardées
[58/1023] kyla7 | createdAt=2025-01-10 21:53:34.943000+00:00 | 48 parties sauvegardées
[59/1023] Whatever_ugh1 | createdAt=2024-04-15 08:42:43.138000+00:00 | 750 parties sauvegardées
[60/1023] jumpywizard30 | createdAt=2023-03-09 05:12:26.549000+00:00 | 244 parties sauvegardées
[61/1023] demirkan_46 | createdAt=2023-12-16 20:05:51.100000+00:00 | 44 parties sauvegardées
[62/1023] The_death_king | createdAt=2023-01-28 02:47:28.149000+00:00 | 82 parties sauvegardées
[63/1023] Tshepiso22 | createdAt=2022-12-22 06:08:29.623000+00:00 | 321 parties sauvegardées
[64/1023] mwglass | createdAt=2016-11-16 18:30:34.201000+00:00 | 0 parties sauvegardées
[65/1023] kirax77 | createdAt=2024-12-05 08:49:01.542000+00:00 | 75 parties sauvegardées
[66/1023] Jamikl | createdAt=2019-02-28 17:42:45.420000+00:00 | 0 parties sauvegardées
[67/1023] Kehinde4885 | createdAt=2020-04-10 18:34:35.018000+00:00 | 0 parties sauvegardées
[68/1023] q_ink | createdAt=2021-07-11 19:37:33.577000+00:00 | 0 parties sauvegardées
[69/1023] Mateusz14K | createdAt=2023-02-13 09:08:34.434000+00:00 | 64 parties sauvegardées
[70/1023] dedkam | createdAt=2021-03-13 19:41:22.394000+00:00 | 0 parties sauvegardées
[71/1023] EgehanGulsoy | createdAt=2023-11-19 17:20:10.496000+00:00 | 349 parties sauvegardées
[72/1023] sajjadghavami | createdAt=2023-12-20 01:44:08.854000+00:00 | 14 parties sauvegardées
[73/1023] MaksYak | createdAt=2023-12-09 17:48:20.356000+00:00 | 565 parties sauvegardées
[74/1023] Parthax | createdAt=2023-06-29 03:02:35.714000+00:00 | 1050 parties sauvegardées
[75/1023] antifurry-x | createdAt=2024-07-12 22:53:24.461000+00:00 | 143 parties sauvegardées
[76/1023] burgerkrig | createdAt=2020-01-31 16:22:47.391000+00:00 | 0 parties sauvegardées
[77/1023] hlltrkoglu | createdAt=2025-01-13 20:27:32.909000+00:00 | 104 parties sauvegardées
[78/1023] Mixo1989 | createdAt=2024-12-14 18:00:43.407000+00:00 | 514 parties sauvegardées
[79/1023] cyan8brian | createdAt=2024-11-02 09:18:13.476000+00:00 | 417 parties sauvegardées
[80/1023] mahdiuip | createdAt=2024-09-16 19:29:06.682000+00:00 | 988 parties sauvegardées
[81/1023] JuriEsipov | createdAt=2023-12-13 15:53:10.889000+00:00 | 1050 parties sauvegardées
[82/1023] Jenil1007 | createdAt=2022-07-31 16:31:49.887000+00:00 | 146 parties sauvegardées
[83/1023] Chuygun | createdAt=2020-12-01 06:53:09.950000+00:00 | 0 parties sauvegardées
[84/1023] Engibarov | createdAt=2024-06-24 11:57:52.091000+00:00 | 1050 parties sauvegardées
[85/1023] Faridov81 | createdAt=2024-03-02 22:05:53.656000+00:00 | 624 parties sauvegardées
[86/1023] ivanov84 | createdAt=2024-10-09 14:03:53.208000+00:00 | 626 parties sauvegardées
[ERREUR] sillangchiiiii: Champ 'createdAt' introuvable dans get_public_data.
[88/1023] pallavibhosale1705 | createdAt=2025-01-05 12:17:23.558000+00:00 | 4 parties sauvegardées
[89/1023] alex16011 | createdAt=2021-01-13 07:35:30.345000+00:00 | 0 parties sauvegardées
[90/1023] pe72dam | createdAt=2021-07-17 09:39:13.196000+00:00 | 38 parties sauvegardées
[91/1023] Rambooooooo | createdAt=2024-10-17 17:53:06.263000+00:00 | 1044 parties sauvegardées
[92/1023] ajayguntreddi | createdAt=2024-01-06 10:43:55.725000+00:00 | 399 parties sauvegardées
[93/1023] funkybob | createdAt=2020-04-28 00:29:49.045000+00:00 | 0 parties sauvegardées
[94/1023] Der-Android | createdAt=2021-09-04 12:22:03.091000+00:00 | 362 parties sauvegardées
[95/1023] Darzius | createdAt=2017-01-03 03:06:26.435000+00:00 | 0 parties sauvegardées
[96/1023] ananyachunduri | createdAt=2022-11-29 23:01:59.387000+00:00 | 105 parties sauvegardées
[97/1023] pradeeme | createdAt=2023-10-23 23:46:35.917000+00:00 | 1 parties sauvegardées
[98/1023] ghostyly | createdAt=2019-11-29 00:46:23.422000+00:00 | 0 parties sauvegardées
[99/1023] NatTheBag | createdAt=2023-04-01 16:38:10.747000+00:00 | 25 parties sauvegardées
[100/1023] silker06 | createdAt=2023-03-20 20:59:15.615000+00:00 | 631 parties sauvegardées
[101/1023] arpan11111 | createdAt=2025-01-15 16:11:17.107000+00:00 | 548 parties sauvegardées
[102/1023] schi1z0puppet | createdAt=2021-03-14 10:02:21.534000+00:00 | 0 parties sauvegardées
[103/1023] mirceah | createdAt=2018-07-22 03:52:38.730000+00:00 | 0 parties sauvegardées
[104/1023] Alicee99 | createdAt=2023-10-06 16:21:10.409000+00:00 | 257 parties sauvegardées
[105/1023] Ahmadou1223 | createdAt=2023-05-09 02:45:57.553000+00:00 | 1050 parties sauvegardées
[106/1023] cheikh_Anta | createdAt=2025-01-14 20:53:05.289000+00:00 | 21 parties sauvegardées
[107/1023] halilatik_0707 | createdAt=2022-04-09 13:28:58.305000+00:00 | 260 parties sauvegardées
[108/1023] kapoentjeaanzee | createdAt=2024-05-27 18:14:04.753000+00:00 | 470 parties sauvegardées
[109/1023] riseofraisins | createdAt=2023-07-13 06:43:11.890000+00:00 | 243 parties sauvegardées
[110/1023] mamikee333 | createdAt=2025-01-15 04:51:55.047000+00:00 | 5 parties sauvegardées
[111/1023] AlanDiego | createdAt=2020-05-04 17:13:19.198000+00:00 | 0 parties sauvegardées
[112/1023] ym09 | createdAt=2022-06-29 19:14:38.642000+00:00 | 566 parties sauvegardées
[113/1023] Typoi_237618484 | createdAt=2025-01-11 18:26:13.872000+00:00 | 69 parties sauvegardées
[114/1023] Mahu265 | createdAt=2024-03-01 01:08:05.095000+00:00 | 19 parties sauvegardées
[115/1023] EsenyaKalinina | createdAt=2024-11-04 10:19:42.072000+00:00 | 130 parties sauvegardées
[116/1023] GriGimn4 | createdAt=2023-11-16 17:07:58.941000+00:00 | 194 parties sauvegardées
[117/1023] nsdp87 | createdAt=2022-01-17 09:58:20.979000+00:00 | 0 parties sauvegardées
[118/1023] Rahevn | createdAt=2023-01-28 13:23:44.785000+00:00 | 31 parties sauvegardées
[119/1023] fyvxhvxgd | createdAt=2023-07-08 07:51:46.989000+00:00 | 23 parties sauvegardées
[120/1023] RohitBhagat | createdAt=2023-09-30 03:46:47.587000+00:00 | 639 parties sauvegardées
[121/1023] IDEJ | createdAt=2024-06-14 06:54:34.706000+00:00 | 109 parties sauvegardées
[122/1023] AP0416 | createdAt=2020-04-27 12:40:56.289000+00:00 | 0 parties sauvegardées
[123/1023] Pedgerr | createdAt=2020-05-21 20:40:16.814000+00:00 | 0 parties sauvegardées
[124/1023] RashidMmutahammil | createdAt=2024-11-23 12:18:23.799000+00:00 | 153 parties sauvegardées
[125/1023] qmrnhll | createdAt=2024-10-24 10:05:02.150000+00:00 | 699 parties sauvegardées
[126/1023] halilibrahimdenizli | createdAt=2024-06-18 07:34:37.096000+00:00 | 1029 parties sauvegardées
[127/1023] delicia1 | createdAt=2022-04-29 13:50:47.854000+00:00 | 0 parties sauvegardées
[128/1023] rahulgopi18 | createdAt=2024-12-22 12:27:03.502000+00:00 | 185 parties sauvegardées
[129/1023] Gr3ml1N | createdAt=2020-01-22 08:29:02.135000+00:00 | 0 parties sauvegardées
[130/1023] masterJA | createdAt=2021-12-14 22:06:55.548000+00:00 | 295 parties sauvegardées
[131/1023] andtorre | createdAt=2024-10-06 15:16:07.563000+00:00 | 1050 parties sauvegardées
[132/1023] aboamer14 | createdAt=2024-09-01 18:43:04.896000+00:00 | 692 parties sauvegardées
[133/1023] EXYZ1 | createdAt=2023-04-04 03:35:24.512000+00:00 | 1050 parties sauvegardées
[134/1023] Tamzyr | createdAt=2020-03-28 15:31:03.408000+00:00 | 0 parties sauvegardées
[135/1023] agawa5000 | createdAt=2019-05-03 11:13:49.988000+00:00 | 0 parties sauvegardées
[136/1023] climbernetik | createdAt=2021-09-29 15:18:18.873000+00:00 | 1 parties sauvegardées
[137/1023] Anaroque | createdAt=2023-11-05 16:11:54.237000+00:00 | 529 parties sauvegardées
[ERREUR] GrzegorzBach: Champ 'createdAt' introuvable dans get_public_data.
[139/1023] HeinzGerhard | createdAt=2024-12-22 06:57:01.815000+00:00 | 1050 parties sauvegardées
[140/1023] MAHDI16-WIN | createdAt=2024-09-05 23:27:31.745000+00:00 | 393 parties sauvegardées
[141/1023] pawnsmove123 | createdAt=2020-08-15 13:14:06.676000+00:00 | 0 parties sauvegardées
[142/1023] OshanSiriwardhana | createdAt=2024-08-18 15:39:05.500000+00:00 | 921 parties sauvegardées
[143/1023] bovaleddu | createdAt=2024-10-02 05:56:29.135000+00:00 | 620 parties sauvegardées
[144/1023] NorAzli | createdAt=2019-11-25 13:31:37.291000+00:00 | 0 parties sauvegardées
[145/1023] c111kin201 | createdAt=2024-01-18 10:39:39.431000+00:00 | 799 parties sauvegardées
[146/1023] Xispo74 | createdAt=2018-12-01 22:38:42.915000+00:00 | 0 parties sauvegardées
[147/1023] Sreevishak | createdAt=2022-08-14 14:44:38.045000+00:00 | 17 parties sauvegardées
[148/1023] Vojimir_Ljubicic | createdAt=2021-01-04 16:08:42.555000+00:00 | 1 parties sauvegardées
[149/1023] milanesoo | createdAt=2024-12-25 00:04:33.629000+00:00 | 16 parties sauvegardées
[150/1023] NikitaShab15 | createdAt=2024-09-07 11:42:26.894000+00:00 | 24 parties sauvegardées
[151/1023] DruTrix | createdAt=2025-01-09 02:23:54.462000+00:00 | 144 parties sauvegardées
[152/1023] lgvgucfvg | createdAt=2025-01-11 15:23:44.349000+00:00 | 162 parties sauvegardées
[153/1023] kardamon8 | createdAt=2024-11-08 08:45:13.486000+00:00 | 131 parties sauvegardées
[154/1023] tebzast | createdAt=2022-09-04 19:45:19.533000+00:00 | 883 parties sauvegardées
[155/1023] Naelmorange | createdAt=2024-12-29 13:04:43.291000+00:00 | 65 parties sauvegardées
[156/1023] Victor_la_Mirandelle | createdAt=2024-12-22 09:43:57.624000+00:00 | 51 parties sauvegardées
[157/1023] claireua | createdAt=2023-11-16 13:05:19.125000+00:00 | 363 parties sauvegardées
[158/1023] A_Vildan | createdAt=2021-12-30 17:41:18.439000+00:00 | 1050 parties sauvegardées
[159/1023] kirill_vladimir0vich | createdAt=2023-11-07 13:36:09.561000+00:00 | 186 parties sauvegardées
[160/1023] anfe1030 | createdAt=2019-05-27 13:03:40.932000+00:00 | 0 parties sauvegardées
[161/1023] Kaporta13 | createdAt=2020-11-15 14:13:35.322000+00:00 | 0 parties sauvegardées
[162/1023] vl9ka | createdAt=2024-08-15 19:49:13.449000+00:00 | 160 parties sauvegardées
[163/1023] muniyal | createdAt=2021-07-25 07:09:11.766000+00:00 | 95 parties sauvegardées
[164/1023] Zhdos | createdAt=2024-09-25 16:42:04.693000+00:00 | 808 parties sauvegardées
[165/1023] sefared | createdAt=2025-01-16 11:38:15.068000+00:00 | 659 parties sauvegardées
[166/1023] shankyyuvi | createdAt=2022-02-06 11:14:16.789000+00:00 | 700 parties sauvegardées
[167/1023] JeanDuvoyage | createdAt=2020-12-30 00:01:15.754000+00:00 | 0 parties sauvegardées
[168/1023] Plampatsch | createdAt=2022-01-06 20:27:01.849000+00:00 | 0 parties sauvegardées
[169/1023] Sowens | createdAt=2015-11-09 19:45:57.874000+00:00 | 0 parties sauvegardées
[170/1023] patel2219 | createdAt=2019-06-25 16:45:39.605000+00:00 | 0 parties sauvegardées
[171/1023] yeahboi123 | createdAt=2024-12-29 19:32:56.134000+00:00 | 180 parties sauvegardées
[172/1023] eRDENiZ2024 | createdAt=2024-07-01 19:59:22.939000+00:00 | 932 parties sauvegardées
[173/1023] demir-kavun | createdAt=2024-07-16 08:18:11.529000+00:00 | 411 parties sauvegardées
[174/1023] kemal_topcu | createdAt=2021-01-30 11:34:40.168000+00:00 | 0 parties sauvegardées
[175/1023] ilsv | createdAt=2022-06-01 07:20:54.698000+00:00 | 0 parties sauvegardées
[176/1023] sayatrhc | createdAt=2024-03-07 13:16:21.092000+00:00 | 865 parties sauvegardées
[177/1023] aash48 | createdAt=2024-08-19 13:44:01.738000+00:00 | 1050 parties sauvegardées
[178/1023] hamidhsjsj | createdAt=2023-09-18 16:54:05.080000+00:00 | 95 parties sauvegardées
[179/1023] meysam147 | createdAt=2024-02-16 05:04:09.413000+00:00 | 742 parties sauvegardées
[180/1023] chexmeight3452 | createdAt=2024-08-18 20:07:44.022000+00:00 | 101 parties sauvegardées
[ERREUR] exocet24: Champ 'createdAt' introuvable dans get_public_data.
[182/1023] Jazmine_ooko | createdAt=2024-04-29 08:18:47.053000+00:00 | 69 parties sauvegardées
[183/1023] ARISTEAMAV | createdAt=2024-09-30 21:26:28.812000+00:00 | 1043 parties sauvegardées
[184/1023] jansiebold | createdAt=2019-05-31 22:07:03.711000+00:00 | 0 parties sauvegardées
[185/1023] Betepok79 | createdAt=2020-02-22 23:37:28.700000+00:00 | 0 parties sauvegardées
[186/1023] jesusvega2025 | createdAt=2025-01-06 21:14:51.300000+00:00 | 3 parties sauvegardées
[187/1023] EREN2017 | createdAt=2023-11-25 14:46:31.798000+00:00 | 146 parties sauvegardées
[188/1023] King-Andreas | createdAt=2022-02-19 17:31:47.823000+00:00 | 1050 parties sauvegardées
[189/1023] rubraspa2do | createdAt=2024-04-02 20:08:12.749000+00:00 | 980 parties sauvegardées
[190/1023] threlderwand | createdAt=2021-12-12 06:52:22.783000+00:00 | 245 parties sauvegardées
[191/1023] mmadeen7 | createdAt=2024-12-07 19:13:19.268000+00:00 | 63 parties sauvegardées
[192/1023] mansouralizadeh | createdAt=2022-06-28 17:06:25.534000+00:00 | 1049 parties sauvegardées
[193/1023] athena27626 | createdAt=2023-01-24 15:54:01.102000+00:00 | 1050 parties sauvegardées
[ERREUR] Cheeseinmybeard: Champ 'createdAt' introuvable dans get_public_data.
[195/1023] soutee | createdAt=2020-11-16 14:40:36.417000+00:00 | 0 parties sauvegardées
[196/1023] dhrex | createdAt=2024-08-16 14:21:08.635000+00:00 | 43 parties sauvegardées
[197/1023] komugiee | createdAt=2024-07-30 19:11:06.651000+00:00 | 1049 parties sauvegardées
[198/1023] Chesstday365 | createdAt=2024-10-15 12:49:45.239000+00:00 | 1049 parties sauvegardées
[199/1023] PeterPopper | createdAt=2023-12-04 15:50:01.137000+00:00 | 528 parties sauvegardées
[200/1023] Jinaychess | createdAt=2022-08-20 15:25:31.963000+00:00 | 183 parties sauvegardées
[201/1023] borhan04 | createdAt=2023-11-13 07:38:34.096000+00:00 | 0 parties sauvegardées
[202/1023] chinexy | createdAt=2024-12-19 13:37:32.431000+00:00 | 15 parties sauvegardées
[203/1023] HELMY11 | createdAt=2021-03-04 11:42:14.562000+00:00 | 0 parties sauvegardées
[204/1023] tiger1230A | createdAt=2024-12-29 13:36:31.459000+00:00 | 163 parties sauvegardées
[205/1023] Abo_Omar122 | createdAt=2024-02-29 20:07:37.640000+00:00 | 833 parties sauvegardées
[206/1023] arman_nj | createdAt=2023-06-19 17:24:05.795000+00:00 | 209 parties sauvegardées
[207/1023] Nikan_avan | createdAt=2024-04-14 15:35:23.941000+00:00 | 747 parties sauvegardées
[208/1023] Otez_prekrasnogo_reb | createdAt=2024-12-16 17:21:34.411000+00:00 | 772 parties sauvegardées
[209/1023] PITCHOOPE | createdAt=2024-11-06 22:19:31.640000+00:00 | 1050 parties sauvegardées
[210/1023] Emile0398 | createdAt=2023-07-28 01:03:00.604000+00:00 | 112 parties sauvegardées
[211/1023] semerci242 | createdAt=2020-02-26 13:11:21.657000+00:00 | 0 parties sauvegardées
[212/1023] Mukanbet1111 | createdAt=2021-03-21 17:23:45.713000+00:00 | 0 parties sauvegardées
[213/1023] BrahmsLisztsynthesis | createdAt=2024-08-28 21:34:38.507000+00:00 | 707 parties sauvegardées
[214/1023] chesskaarma | createdAt=2024-11-16 17:36:45.322000+00:00 | 330 parties sauvegardées
[215/1023] Egor2015G | createdAt=2021-03-28 13:08:41.328000+00:00 | 0 parties sauvegardées
[216/1023] Ikarysy | createdAt=2024-09-16 18:40:26.227000+00:00 | 423 parties sauvegardées
[217/1023] naveendilshan | createdAt=2022-05-07 12:18:30.506000+00:00 | 12 parties sauvegardées
[218/1023] Adriel-ChildOfGod | createdAt=2024-03-24 10:24:54.222000+00:00 | 68 parties sauvegardées
[219/1023] ZRJ890 | createdAt=2024-03-09 13:44:31.216000+00:00 | 19 parties sauvegardées
[220/1023] bonifathiy | createdAt=2024-12-18 09:03:44.191000+00:00 | 1029 parties sauvegardées
[221/1023] meeshgun | createdAt=2024-11-15 13:24:06.106000+00:00 | 1047 parties sauvegardées
[222/1023] Ncank | createdAt=2024-08-10 13:02:57.974000+00:00 | 1001 parties sauvegardées

In [17]:
raw_games_by_player = load_raw_games_by_player_from_directory(RAW_GAMES_BY_PLAYER_DIR)

print(f"raw_games_by_player reconstruit depuis {RAW_GAMES_BY_PLAYER_DIR}")
print(f"{len(raw_games_by_player)} joueurs chargés depuis le disque")

raw_games_by_player reconstruit depuis ..\data\raw\by_player
1827 joueurs chargés depuis le disque

## 4. Construire ou recharger `player_games_raw`

Ici, on passe du JSON API brut à la table analytique.
La fonction `build_player_games_raw_from_api_dump(...)` doit :

- appeler `build_player_games(games)` pour chaque joueur
- concaténer les DataFrames
- faire `drop_duplicates(subset=['player_id', 'game_id'])`

In [18]:
if USE_EXISTING_PLAYER_GAMES_RAW_JSON and PLAYER_GAMES_RAW_JSON_PATH.exists():
    player_games_raw = load_player_games_raw(PLAYER_GAMES_RAW_JSON_PATH)
    print(f'player_games_raw rechargé depuis {PLAYER_GAMES_RAW_JSON_PATH}')
else:
    player_games_raw = build_player_games_raw_from_api_dump(raw_games_by_player)
    save_player_games_raw(player_games_raw, PLAYER_GAMES_RAW_JSON_PATH)
    print(f'player_games_raw sauvegardé dans {PLAYER_GAMES_RAW_JSON_PATH}')

player_games_raw sauvegardé dans ..\data\raw\player_games_raw.json

In [19]:
print(player_games_raw.shape)
display(player_games_raw.head())

(1112932, 22)

,game_id,datetime_utc,weekday,player_id,player_name,opponent_id,opponent_name,color_player,result_player,elo_player_before,...,termination_type,has_increment,opening_family,opening_eco,opening_name,ply_count,perf,speed,rated,source
0,suIoXxvP,2025-01-09 19:39:21.207000+00:00,3,a123krowy,A123krowy,denchik1934,Denchik1934,white,0.0,1500,...,resign,1,Queen’s Pawn Systems,D00,Queen's Pawn Game,40,rapid,rapid,True,pool
1,suIoXxvP,2025-01-09 19:39:21.207000+00:00,3,denchik1934,Denchik1934,a123krowy,A123krowy,black,1.0,1505,...,resign,1,Queen’s Pawn Systems,D00,Queen's Pawn Game,40,rapid,rapid,True,pool
2,SgxvW53p,2025-01-09 19:50:32.757000+00:00,3,hlk1985,HLK1985,a123krowy,A123krowy,white,0.5,1108,...,stalemate,1,Queen’s Pawn Systems,D01,"Rapport-Jobava System, with e6",92,rapid,rapid,True,pool
3,SgxvW53p,2025-01-09 19:50:32.757000+00:00,3,a123krowy,A123krowy,hlk1985,HLK1985,black,0.5,1267,...,stalemate,1,Queen’s Pawn Systems,D01,"Rapport-Jobava System, with e6",92,rapid,rapid,True,pool
4,ehUwi7BW,2025-01-09 20:19:41.903000+00:00,3,lifeisachessgame,lifeisachessgame,a123krowy,A123krowy,white,1.0,1357,...,timeout,1,Petrov Defense,C42,Petrov's Defense: Three Knights Game,9,rapid,rapid,True,pool

In [20]:
print('Nb joueurs dans player_games_raw :', player_games_raw['player_id'].nunique())
print('Doublons (player_id, game_id) :', player_games_raw.duplicated(subset=['player_id', 'game_id']).sum())

Nb joueurs dans player_games_raw : 296738
Doublons (player_id, game_id) : 0

## 5. Appliquer la sélection finale

In [21]:
selection_config = PlayerSelectionConfig(
    min_games_in_window=200,
    max_games_in_window=1000,
    burnin_games=20,
    min_initial_elo=1000,
    max_initial_elo=1400,
    observation_window_days=183,
)

player_games_selected = select_player_games(
    player_games_raw,
    config=selection_config,
    verbose=True,
)

[Initial] rows=1,112,932 | players=296,738
[Après filtres bruts] rows=1,112,932 | players=296,738
[Après suppression des 20 premières parties rapid/rated/finished] rows=541,966 | players=1,685
[Après filtre Elo initial [1000, 1400]] rows=337,434 | players=1,150
[Après fenêtre d'observation de 183 jours] rows=335,570 | players=1,150
[Après filtre nombre de parties [200, 1000]] rows=149,251 | players=298

[Résumé final]
Joueurs retenus : 298
Lignes retenues  : 149,251
Nb de parties par joueur :
count    298.000000
mean     500.842282
std      214.950653
min      200.000000
25%      322.250000
50%      470.500000
75%      665.000000
max      998.000000
Name: game_id, dtype: float64

Elo initial dans la fenêtre :
count     298.000000
mean     1160.503356
std       101.031457
min      1000.000000
25%      1083.000000
50%      1149.500000
75%      1243.000000
max      1400.000000
Name: elo_player_before, dtype: float64

## 6. Inspecter les résultats

In [22]:
print('Nb joueurs retenus :', player_games_selected['player_id'].nunique())
print(player_games_selected.groupby('player_id')['game_id'].count().describe())
display(player_games_selected[['player_id', 'elo_player_before']].head())

Nb joueurs retenus : 298
count    298.000000
mean     500.842282
std      214.950653
min      200.000000
25%      322.250000
50%      470.500000
75%      665.000000
max      998.000000
Name: game_id, dtype: float64

   player_id  elo_player_before
0  a123krowy               1071
1  a123krowy               1088
2  a123krowy               1072
3  a123krowy               1053
4  a123krowy               1070

In [23]:
selected_players = sorted(player_games_selected['player_id'].unique())
print(len(selected_players))
print(selected_players[:30])

298
['a123krowy', 'a5_tulatrain-moscow', 'abadan007', 'abasssm', 'abdeerrahim', 'abiramy_ruban', 'abo_omar122', 'aboadel2025', 'aboamer14', 'ad0105', 'adalbertus_szachmat', 'adsiw', 'ahmad189', 'ahmed_9669', 'ahmetsnll', 'ajayguntreddi', 'albina228', 'aleksey5001', 'alessandro949', 'alexanderororo', 'alexey963', 'alexsur99', 'alexviat', 'alicee99', 'aluschirm', 'ameliajuniorchess', 'amir500a', 'amir_klv98', 'anaroque', 'anje36']

In [24]:
games_per_player = player_games_selected.groupby('player_id')['game_id'].count().sort_values(ascending=False)
display(games_per_player.head(143))

player_id
alessandro949        998
erik_osl             995
don81                990
maxicuro             979
mahdiuip             968
                    ...
rroseselavie         493
rifat-33             491
maksimcapsamun198    491
abasssm              485
bendjedidi_aymen2    483
Name: game_id, Length: 143, dtype: int64

## 7. Sauvegardes complémentaires optionnelles

Si tu veux plus tard, tu pourras ajouter ici :

- sauvegarde de `player_games_selected`
- export de la liste finale des joueurs retenus
- statistiques résumées

In [25]:

# 1. Sauvegarde du dataset final sélectionné
save_player_games_selected(
    player_games_selected,
    PLAYER_GAMES_SELECTED_JSON_PATH,
)
print(f"player_games_selected sauvegardé dans {PLAYER_GAMES_SELECTED_JSON_PATH}")

# 2. Sauvegarde de la liste des joueurs retenus
selected_players = sorted(player_games_selected["player_id"].unique())
SELECTED_PLAYERS_TXT_PATH.parent.mkdir(parents=True, exist_ok=True)
SELECTED_PLAYERS_TXT_PATH.write_text("\n".join(selected_players), encoding="utf-8")
print(f"Liste des joueurs retenus sauvegardée dans {SELECTED_PLAYERS_TXT_PATH}")

# 3. Sauvegarde d'un résumé de sélection
games_per_player = player_games_selected.groupby("player_id")["game_id"].count()
first_games = (
    player_games_selected
    .sort_values(["player_id", "datetime_utc", "game_id"])
    .groupby("player_id", as_index=False)
    .first()
)

selection_summary = {
    "n_players": int(player_games_selected["player_id"].nunique()),
    "n_rows": int(len(player_games_selected)),
    "games_per_player": {
        "count": float(games_per_player.count()),
        "mean": float(games_per_player.mean()),
        "std": float(games_per_player.std()),
        "min": float(games_per_player.min()),
        "25%": float(games_per_player.quantile(0.25)),
        "50%": float(games_per_player.quantile(0.50)),
        "75%": float(games_per_player.quantile(0.75)),
        "max": float(games_per_player.max()),
    },
    "initial_elo_in_window": {
        "count": float(first_games["elo_player_before"].count()),
        "mean": float(first_games["elo_player_before"].mean()),
        "std": float(first_games["elo_player_before"].std()),
        "min": float(first_games["elo_player_before"].min()),
        "25%": float(first_games["elo_player_before"].quantile(0.25)),
        "50%": float(first_games["elo_player_before"].quantile(0.50)),
        "75%": float(first_games["elo_player_before"].quantile(0.75)),
        "max": float(first_games["elo_player_before"].max()),
    },
}

SELECTION_SUMMARY_JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
with SELECTION_SUMMARY_JSON_PATH.open("w", encoding="utf-8") as f:
    json.dump(selection_summary, f, ensure_ascii=False, indent=2)

print(f"Résumé de sélection sauvegardé dans {SELECTION_SUMMARY_JSON_PATH}")



selection_config_dict = {
    "min_games_after_burnin": 200,
    "max_games": 1000,
    "burnin_games": 20,
    "min_initial_elo": 1000,
    "max_initial_elo": 1400,
    "observation_window_days": 183,
}


with (SELECTION_CONFIG_JSON_PATH).open("w", encoding="utf-8") as f:
    json.dump(selection_config_dict, f, indent=2)

player_games_selected sauvegardé dans ..\data\selected\player_games_selected.json
Liste des joueurs retenus sauvegardée dans ..\data\selected\selected_players.txt
Résumé de sélection sauvegardé dans ..\data\selected\selection_summary.json

In [26]:
assert player_games_selected["player_id"].nunique() > 0
assert not player_games_selected.empty
assert player_games_selected.duplicated(subset=["player_id", "game_id"]).sum() == 0

# 8. Création des parties enrichies

In [38]:
from src.features.game_features import build_game_features

games_final = build_game_features(player_games_selected)

print("Shape games_final :", games_final.shape)
display(games_final.head())

Shape games_final : (149251, 45)

,game_id,datetime_utc,weekday,player_id,player_name,opponent_id,opponent_name,color_player,result_player,elo_player_before,...,session_delay,session_discrete_delay,day_date_utc,day_n_games,day_score,day_position,week_id,week_n_games,week_score,week_position
0,pP77HkPM,2025-01-18 09:07:25.062000+00:00,5,a123krowy,A123krowy,himanshi2015,Himanshi2015,white,1.0,1071,...,NaN,NaN,2025-01-18,1,1.00,0,2025-W03,11,0.409091,0
1,6HwUpUTM,2025-01-19 07:55:33.921000+00:00,6,a123krowy,A123krowy,toni66,toni66,black,0.0,1088,...,82088.859,B,2025-01-19,10,0.35,0,2025-W03,11,0.409091,1
2,HESDVI1Z,2025-01-19 08:13:55.722000+00:00,6,a123krowy,A123krowy,gabrielc400,gabrielc400,black,0.0,1072,...,82088.859,B,2025-01-19,10,0.35,1,2025-W03,11,0.409091,2
3,n7s1jj71,2025-01-19 08:18:30.434000+00:00,6,a123krowy,A123krowy,neggm1,neggm1,black,1.0,1053,...,82088.859,B,2025-01-19,10,0.35,2,2025-W03,11,0.409091,3
4,DIiwuSXs,2025-01-19 09:29:37.424000+00:00,6,a123krowy,A123krowy,huseyinaltan,HUSEYINALTAN,white,0.0,1070,...,4266.990,A,2025-01-19,10,0.35,3,2025-W03,11,0.409091,4

## 8.1 Quelques tests

In [39]:
assert len(games_final) == len(player_games_selected), \
    f"Perte de lignes : {len(player_games_selected)} → {len(games_final)}"

duplicates = games_final.duplicated(subset=["player_id", "game_id"]).sum()
assert duplicates == 0, f"Doublons détectés : {duplicates}"

session_stats = games_final.groupby("player_id")["session_id"].nunique()

print(session_stats.describe())

count    298.000000
mean     185.419463
std      105.018398
min       21.000000
25%      110.000000
50%      164.500000
75%      248.000000
max      551.000000
Name: session_id, dtype: float64

In [29]:
delay_stats = games_final["delay_previous_game"].describe()
print(delay_stats)

count    1.489530e+05
mean     2.499709e+04
std      1.442821e+05
min      3.091000e+00
25%      4.665940e+02
50%      1.128560e+03
75%      1.285118e+04
max      1.442312e+07
Name: delay_previous_game, dtype: float64

In [41]:
display(
    games_final[
        ["player_id", "game_id", "streak_before", "streak_after"]
    ].head(20)
)

    player_id   game_id  streak_before  streak_after
0   a123krowy  pP77HkPM            NaN             1
1   a123krowy  6HwUpUTM            1.0            -1
2   a123krowy  HESDVI1Z           -1.0            -2
3   a123krowy  n7s1jj71           -2.0             1
4   a123krowy  DIiwuSXs            1.0            -1
5   a123krowy  rkFHTF34           -1.0             1
6   a123krowy  wIaJVpXJ            1.0            -1
7   a123krowy  T7dz4wQu           -1.0            -2
8   a123krowy  AQExDB2f           -2.0             0
9   a123krowy  iS5YGelz            0.0            -1
10  a123krowy  bVRUc5GO           -1.0             1
11  a123krowy  GShzUZ9i            1.0            -1
12  a123krowy  ZY0VsF5H           -1.0            -2
13  a123krowy  NZx1aiL5           -2.0            -3
14  a123krowy  1p0CPZNK           -3.0            -4
15  a123krowy  wBA5xFuF           -4.0             0
16  a123krowy  kfn5DiGZ            0.0            -1
17  a123krowy  USk5q7zo           -1.0             1
18  a123krowy  ct4f6VTp            1.0            -1
19  a123krowy  oIlFd5Wz           -1.0            -2

In [43]:
display(
    games_final[["day_n_games", "week_n_games"]].describe()
)

         day_n_games   week_n_games
count  149251.000000  149251.000000
mean       11.534965      49.945964
std         9.675731      36.830471
min         1.000000       1.000000
25%         5.000000      25.000000
50%         9.000000      41.000000
75%        15.000000      64.000000
max        76.000000     293.000000

## 8.2 Sauvegarde des parties

In [ ]:


GAMES_FINAL_JSON_PATH.parent.mkdir(parents=True, exist_ok=True)

save_player_games_selected(
    games_final,
    GAMES_FINAL_JSON_PATH,
)

print(f"games_final sauvegardé dans {GAMES_FINAL_JSON_PATH}")

games_final sauvegardé dans ..\data\enriched\games_final.json

# 9. Création des données niveau joueur

In [8]:
games_final = load_player_games_selected(GAMES_FINAL_JSON_PATH)

games_final.head(20)

,game_id,datetime_utc,weekday,player_id,player_name,opponent_id,opponent_name,color_player,result_player,elo_player_before,...,session_delay,session_discrete_delay,day_date_utc,day_n_games,day_score,day_position,week_id,week_n_games,week_score,week_position
0,pP77HkPM,2025-01-18 09:07:25.062000+00:00,5,a123krowy,A123krowy,himanshi2015,Himanshi2015,white,1.0,1071,...,NaN,NaN,2025-01-18,1,1.00,0,2025-W03,11,0.409091,0
1,6HwUpUTM,2025-01-19 07:55:33.921000+00:00,6,a123krowy,A123krowy,toni66,toni66,black,0.0,1088,...,82088.859,B,2025-01-19,10,0.35,0,2025-W03,11,0.409091,1
2,HESDVI1Z,2025-01-19 08:13:55.722000+00:00,6,a123krowy,A123krowy,gabrielc400,gabrielc400,black,0.0,1072,...,82088.859,B,2025-01-19,10,0.35,1,2025-W03,11,0.409091,2
3,n7s1jj71,2025-01-19 08:18:30.434000+00:00,6,a123krowy,A123krowy,neggm1,neggm1,black,1.0,1053,...,82088.859,B,2025-01-19,10,0.35,2,2025-W03,11,0.409091,3
4,DIiwuSXs,2025-01-19 09:29:37.424000+00:00,6,a123krowy,A123krowy,huseyinaltan,HUSEYINALTAN,white,0.0,1070,...,4266.990,A,2025-01-19,10,0.35,3,2025-W03,11,0.409091,4
5,rkFHTF34,2025-01-19 10:26:22.007000+00:00,6,a123krowy,A123krowy,rahith_jalan,Rahith_Jalan,black,1.0,1057,...,4266.990,A,2025-01-19,10,0.35,4,2025-W03,11,0.409091,5
6,wIaJVpXJ,2025-01-19 11:09:06.883000+00:00,6,a123krowy,A123krowy,diman_zzz,Diman_ZzZ,white,0.0,1071,...,4266.990,A,2025-01-19,10,0.35,5,2025-W03,11,0.409091,6
7,T7dz4wQu,2025-01-19 18:27:20.702000+00:00,6,a123krowy,A123krowy,rajab2016,Rajab2016,white,0.0,1058,...,26293.819,B,2025-01-19,10,0.35,6,2025-W03,11,0.409091,7
8,AQExDB2f,2025-01-19 18:36:00.432000+00:00,6,a123krowy,A123krowy,josemanuelmm,JoseManuelMM,black,0.5,1044,...,26293.819,B,2025-01-19,10,0.35,7,2025-W03,11,0.409091,8
9,iS5YGelz,2025-01-19 19:04:10.214000+00:00,6,a123krowy,A123krowy,simonebruscino,SimoneBruscino,white,0.0,1042,...,26293.819,B,2025-01-19,10,0.35,8,2025-W03,11,0.409091,9
10,bVRUc5GO,2025-01-19 19:35:21.574000+00:00,6,a123krowy,A123krowy,isenn_walker,Isenn_Walker,black,1.0,1027,...,26293.819,B,2025-01-19,10,0.35,9,2025-W03,11,0.409091,10
11,GShzUZ9i,2025-01-20 17:13:54.853000+00:00,0,a123krowy,A123krowy,fishman90,Fishman90,white,0.0,1038,...,77913.279,B,2025-01-20,5,0.10,0,2025-W04,40,0.275000,0
12,ZY0VsF5H,2025-01-20 17:42:25.958000+00:00,0,a123krowy,A123krowy,megakalce,megakalce,black,0.0,1029,...,77913.279,B,2025-01-20,5,0.10,1,2025-W04,40,0.275000,1
13,NZx1aiL5,2025-01-20 17:49:14.840000+00:00,0,a123krowy,A123krowy,sara_ramezanpour,sara_ramezanpour,black,0.0,1017,...,77913.279,B,2025-01-20,5,0.10,2,2025-W04,40,0.275000,2
14,1p0CPZNK,2025-01-20 18:59:32.962000+00:00,0,a123krowy,A123krowy,cumali_1,cumali_1,white,0.0,1002,...,4218.122,A,2025-01-20,5,0.10,3,2025-W04,40,0.275000,3
15,wBA5xFuF,2025-01-20 19:11:46.655000+00:00,0,a123krowy,A123krowy,shaxo_jakiag,shaxo_jakiag,black,0.5,995,...,4218.122,A,2025-01-20,5,0.10,4,2025-W04,40,0.275000,4
16,kfn5DiGZ,2025-01-21 19:26:18.788000+00:00,1,a123krowy,A123krowy,portablejumper,portablejumper,black,0.0,995,...,87272.133,C,2025-01-21,2,0.50,0,2025-W04,40,0.275000,5
17,USk5q7zo,2025-01-21 19:56:49.753000+00:00,1,a123krowy,A123krowy,minemikimajk,MineMikiMajk,white,1.0,985,...,87272.133,C,2025-01-21,2,0.50,1,2025-W04,40,0.275000,6
18,ct4f6VTp,2025-01-22 16:16:47.889000+00:00,2,a123krowy,A123krowy,s2w0l,s2w0l,black,0.0,993,...,73198.136,B,2025-01-22,8,0.25,0,2025-W04,40,0.275000,7
19,oIlFd5Wz,2025-01-22 16:20:56.143000+00:00,2,a123krowy,A123krowy,somaraddi,somaraddi,white,0.0,985,...,73198.136,B,2025-01-22,8,0.25,1,2025-W04,40,0.275000,8

In [ ]:
from src.features.player_features import build_player_features
from src.labels.progression import build_progression_labels

# 1. Features joueur
player_features = build_player_features(games_final)

# 2. Labels de progression
progression_labels = build_progression_labels(games_final)

# 3. Merge final
final_dataset = player_features.merge(
    progression_labels,
    on="player_id",
    how="inner"
)

player_features : (298, 30)
progression_labels : (298, 5)
final_dataset : (298, 34)

,player_id,mean_ply_count,main_opening_white,main_opening_black,opening_diversity,opening_concentration,abandon_rate,time_loss_rate,draw_ratio,score_when_winstreak,...,entropy_sessions_interval,mean_games_per_session,cv_games_per_session,increment_game_ratio,weekday_bias,color_bias,session_length_performance_slope,within_session_performance_slope,games_per_day_performance_slope,games_per_week_performance_slope
0,a123krowy,41.511269,Queen’s Pawn Systems,King’s Pawn Games / Bishop’s Opening / Vienna,1.498863,0.444997,0.386714,0.021352,0.035587,0.536313,...,1.218249,5.078313,0.909771,0.996441,-0.028967,0.118548,0.006886,0.023772,0.003289,0.001328
1,a5_tulatrain-moscow,47.283871,King’s Gambit,Sicilian,1.693547,0.498364,0.390323,0.038710,0.027419,0.347059,...,1.141608,2.695652,0.912212,0.085484,-0.053779,0.079765,0.023228,-0.071883,0.009776,0.001818
2,abadan007,71.824885,Italian Game & Two Knights Defense,Italian Game & Two Knights Defense,2.434890,0.225493,0.036866,0.018433,0.032258,0.480000,...,1.313033,1.486301,0.592560,1.000000,-0.092144,-0.046084,-0.125320,0.307955,-0.030455,-0.001012
3,abasssm,45.824742,King’s Pawn Games / Bishop’s Opening / Vienna,King’s Pawn Games / Bishop’s Opening / Vienna,2.261723,0.238830,0.274227,0.030928,0.014433,0.500000,...,1.294544,3.368056,0.827018,0.000000,-0.002235,0.102959,0.004610,0.026876,0.001997,0.000547
4,abdeerrahim,63.962672,Italian Game & Two Knights Defense,Modern / Robatsch / Pirc,2.108971,0.359022,0.204322,0.041257,0.023576,0.568000,...,1.078820,2.203463,0.811527,0.009823,0.003827,0.017504,0.011173,0.011297,0.005349,-0.001877

,player_id,elo_gain,elo_gain_per_game,elo_slope_per_game,elo_slope_per_day
0,a123krowy,-376.0,-0.446556,0.003464,0.297313
1,a5_tulatrain-moscow,-133.0,-0.214863,-0.241720,-1.013004
2,abadan007,39.0,0.180556,0.151171,0.237955
3,abasssm,21.0,0.043388,0.166094,0.448836
4,abdeerrahim,136.0,0.267717,0.268417,0.892955

,player_id,mean_ply_count,main_opening_white,main_opening_black,opening_diversity,opening_concentration,abandon_rate,time_loss_rate,draw_ratio,score_when_winstreak,...,weekday_bias,color_bias,session_length_performance_slope,within_session_performance_slope,games_per_day_performance_slope,games_per_week_performance_slope,elo_gain,elo_gain_per_game,elo_slope_per_game,elo_slope_per_day
0,a123krowy,41.511269,Queen’s Pawn Systems,King’s Pawn Games / Bishop’s Opening / Vienna,1.498863,0.444997,0.386714,0.021352,0.035587,0.536313,...,-0.028967,0.118548,0.006886,0.023772,0.003289,0.001328,-376.0,-0.446556,0.003464,0.297313
1,a5_tulatrain-moscow,47.283871,King’s Gambit,Sicilian,1.693547,0.498364,0.390323,0.038710,0.027419,0.347059,...,-0.053779,0.079765,0.023228,-0.071883,0.009776,0.001818,-133.0,-0.214863,-0.241720,-1.013004
2,abadan007,71.824885,Italian Game & Two Knights Defense,Italian Game & Two Knights Defense,2.434890,0.225493,0.036866,0.018433,0.032258,0.480000,...,-0.092144,-0.046084,-0.125320,0.307955,-0.030455,-0.001012,39.0,0.180556,0.151171,0.237955
3,abasssm,45.824742,King’s Pawn Games / Bishop’s Opening / Vienna,King’s Pawn Games / Bishop’s Opening / Vienna,2.261723,0.238830,0.274227,0.030928,0.014433,0.500000,...,-0.002235,0.102959,0.004610,0.026876,0.001997,0.000547,21.0,0.043388,0.166094,0.448836
4,abdeerrahim,63.962672,Italian Game & Two Knights Defense,Modern / Robatsch / Pirc,2.108971,0.359022,0.204322,0.041257,0.023576,0.568000,...,0.003827,0.017504,0.011173,0.011297,0.005349,-0.001877,136.0,0.267717,0.268417,0.892955

In [12]:

print("player_features :", player_features.shape)
print("progression_labels :", progression_labels.shape)
print("final_dataset :", final_dataset.shape)

display(player_features.head())
display(progression_labels.head())
display(final_dataset.head())

player_features : (298, 30)
progression_labels : (298, 5)
final_dataset : (298, 34)

,player_id,mean_ply_count,main_opening_white,main_opening_black,opening_diversity,opening_concentration,abandon_rate,time_loss_rate,draw_ratio,score_when_winstreak,...,entropy_sessions_interval,mean_games_per_session,cv_games_per_session,increment_game_ratio,weekday_bias,color_bias,session_length_performance_slope,within_session_performance_slope,games_per_day_performance_slope,games_per_week_performance_slope
0,a123krowy,41.511269,Queen’s Pawn Systems,King’s Pawn Games / Bishop’s Opening / Vienna,1.498863,0.444997,0.386714,0.021352,0.035587,0.536313,...,1.218249,5.078313,0.909771,0.996441,-0.028967,0.118548,0.006886,0.023772,0.003289,0.001328
1,a5_tulatrain-moscow,47.283871,King’s Gambit,Sicilian,1.693547,0.498364,0.390323,0.038710,0.027419,0.347059,...,1.141608,2.695652,0.912212,0.085484,-0.053779,0.079765,0.023228,-0.071883,0.009776,0.001818
2,abadan007,71.824885,Italian Game & Two Knights Defense,Italian Game & Two Knights Defense,2.434890,0.225493,0.036866,0.018433,0.032258,0.480000,...,1.313033,1.486301,0.592560,1.000000,-0.092144,-0.046084,-0.125320,0.307955,-0.030455,-0.001012
3,abasssm,45.824742,King’s Pawn Games / Bishop’s Opening / Vienna,King’s Pawn Games / Bishop’s Opening / Vienna,2.261723,0.238830,0.274227,0.030928,0.014433,0.500000,...,1.294544,3.368056,0.827018,0.000000,-0.002235,0.102959,0.004610,0.026876,0.001997,0.000547
4,abdeerrahim,63.962672,Italian Game & Two Knights Defense,Modern / Robatsch / Pirc,2.108971,0.359022,0.204322,0.041257,0.023576,0.568000,...,1.078820,2.203463,0.811527,0.009823,0.003827,0.017504,0.011173,0.011297,0.005349,-0.001877

,player_id,elo_gain,elo_gain_per_game,elo_slope_per_game,elo_slope_per_day
0,a123krowy,-376.0,-0.446556,0.003464,0.297313
1,a5_tulatrain-moscow,-133.0,-0.214863,-0.241720,-1.013004
2,abadan007,39.0,0.180556,0.151171,0.237955
3,abasssm,21.0,0.043388,0.166094,0.448836
4,abdeerrahim,136.0,0.267717,0.268417,0.892955

,player_id,mean_ply_count,main_opening_white,main_opening_black,opening_diversity,opening_concentration,abandon_rate,time_loss_rate,draw_ratio,score_when_winstreak,...,weekday_bias,color_bias,session_length_performance_slope,within_session_performance_slope,games_per_day_performance_slope,games_per_week_performance_slope,elo_gain,elo_gain_per_game,elo_slope_per_game,elo_slope_per_day
0,a123krowy,41.511269,Queen’s Pawn Systems,King’s Pawn Games / Bishop’s Opening / Vienna,1.498863,0.444997,0.386714,0.021352,0.035587,0.536313,...,-0.028967,0.118548,0.006886,0.023772,0.003289,0.001328,-376.0,-0.446556,0.003464,0.297313
1,a5_tulatrain-moscow,47.283871,King’s Gambit,Sicilian,1.693547,0.498364,0.390323,0.038710,0.027419,0.347059,...,-0.053779,0.079765,0.023228,-0.071883,0.009776,0.001818,-133.0,-0.214863,-0.241720,-1.013004
2,abadan007,71.824885,Italian Game & Two Knights Defense,Italian Game & Two Knights Defense,2.434890,0.225493,0.036866,0.018433,0.032258,0.480000,...,-0.092144,-0.046084,-0.125320,0.307955,-0.030455,-0.001012,39.0,0.180556,0.151171,0.237955
3,abasssm,45.824742,King’s Pawn Games / Bishop’s Opening / Vienna,King’s Pawn Games / Bishop’s Opening / Vienna,2.261723,0.238830,0.274227,0.030928,0.014433,0.500000,...,-0.002235,0.102959,0.004610,0.026876,0.001997,0.000547,21.0,0.043388,0.166094,0.448836
4,abdeerrahim,63.962672,Italian Game & Two Knights Defense,Modern / Robatsch / Pirc,2.108971,0.359022,0.204322,0.041257,0.023576,0.568000,...,0.003827,0.017504,0.011173,0.011297,0.005349,-0.001877,136.0,0.267717,0.268417,0.892955

## 9.1 Quelques tests

In [13]:
assert player_features["player_id"].nunique() == len(player_features), \
    "player_features ne contient pas exactement une ligne par joueur."

assert progression_labels["player_id"].nunique() == len(progression_labels), \
    "progression_labels ne contient pas exactement une ligne par joueur."

In [14]:
n_final = final_dataset["player_id"].nunique()
n_feat = player_features["player_id"].nunique()
n_prog = progression_labels["player_id"].nunique()

print("Joueurs final_dataset       :", n_final)
print("Joueurs player_features    :", n_feat)
print("Joueurs progression_labels :", n_prog)

assert n_final == n_feat == n_prog, \
    "Les populations de joueurs ne correspondent pas entre les DataFrames."

Joueurs final_dataset       : 298
Joueurs player_features    : 298
Joueurs progression_labels : 298

In [15]:
assert final_dataset["player_id"].nunique() == len(final_dataset), \
    "final_dataset ne contient pas exactement une ligne par joueur."

print("Nb colonnes final_dataset :", final_dataset.shape[1])
print("Colonnes :")
print(final_dataset.columns.tolist())

Nb colonnes final_dataset : 34
Colonnes :
['player_id', 'mean_ply_count', 'main_opening_white', 'main_opening_black', 'opening_diversity', 'opening_concentration', 'abandon_rate', 'time_loss_rate', 'draw_ratio', 'score_when_winstreak', 'score_when_losestreak', 'streak_resilience_bias', 'abandon_rate_when_losestreak', 'time_loss_rate_when_losestreak', 'delay_ratio_when_winstreak', 'delay_ratio_when_losestreak', 'cv_games_interval', 'cv_games_per_day', 'cv_games_per_week', 'cv_sessions_interval', 'entropy_sessions_interval', 'mean_games_per_session', 'cv_games_per_session', 'increment_game_ratio', 'weekday_bias', 'color_bias', 'session_length_performance_slope', 'within_session_performance_slope', 'games_per_day_performance_slope', 'games_per_week_performance_slope', 'elo_gain', 'elo_gain_per_game', 'elo_slope_per_game', 'elo_slope_per_day']

In [16]:
assert final_dataset.duplicated(subset=["player_id"]).sum() == 0, \
    "Doublons détectés sur player_id dans final_dataset."

In [17]:
nan_summary = final_dataset.isna().mean().sort_values(ascending=False)
display(nan_summary[nan_summary > 0])

Series([], dtype: float64)

## 9.2 Sauvegarde du dataset final

In [19]:
FINAL_DATASET_JSON_PATH.parent.mkdir(parents=True, exist_ok=True)

save_player_games_selected(
    final_dataset,
    FINAL_DATASET_JSON_PATH,
)

print(f"final_dataset sauvegardé dans {FINAL_DATASET_JSON_PATH}")

final_dataset sauvegardé dans ..\data\final\final_dataset.json